### PR TITLE
Add vim in image

### PR DESCRIPTION
**Pull request by sylvainar**
Hey there,

It's really hard to fix merge conflicts on weblate without a text editor installed in the image, especially in a k8s cluster when you don't have access to the file on SSH. You are obliged to rsync the conflicting files to your machine, edit them, send rsync them back, it's heavy and your can't `git diff` during edition. I'm proposing via this pull request to add `vim` in the docker image so we can edit files in place (mostly for conflict resolutions).

### CODE REVIEW

**Comment by nijel** [comment]
You are not supposed to fix conflicts inside the container, see https://docs.weblate.org/en/latest/faq.html#how-to-fix-merge-conflicts-in-translations

Also I don't think this is reasonable approach - in the end we would include vim, emacs, nano and everybody else's favorite editor.

**Comment by sylvainar** [comment]
Yup I saw this tutorial, but it didn't work for me: some commits were on the weblate container and still unpushed to its branch so I had to connect remotely in the machine to fix it.

I don't know what is the strategy used for weblate to push commits but it seems that it's pulling origin before pushing, so I couldn't unlock it from the web ui. I couldn't work remotly either because commits were stuck on the machine.

**Comment by nijel** [comment]
You can add Weblate repository as a remote (given you have [Git exporter](https://docs.weblate.org/en/latest/admin/optionals.html#git-exporter)), that's what `git remote add weblate ...` does.

**Comment by sylvainar** [comment]
Ohh okay i missed that.

Let's close this PR then.

**Pull request closed without merging**
