### PR TITLE
Switch to Python 3

### LINKED ISSUE #68: Move to Python 3 and Django 2
There should not be any blockers for switching to Pytho 3 and Django 2 as both are fully supported, so it should be just replacing of all python packages with python3 variants and maybe some changes in the uwsgi setup.

Pull requests welcome :-).

<bountysource-plugin>

---
Want to back this issue? **[Post a bounty on it!](https://www.bountysource.com/issues/52753762-move-to-python-3-and-django-2?utm_campaign=plugin&utm_content=tracker%2F21377293&utm_medium=issues&utm_source=github)** We accept bounties via [Bountysource](https://www.bountysource.com/?utm_campaign=plugin&utm_content=tracker%2F21377293&utm_medium=issues&utm_source=github).
</bountysource-plugin>

### PR DESCRIPTION
**Pull request by nijel**
Fixes #68

Signed-off-by: Michal Čihař <michal@cihar.com>

### CODE REVIEW

**Comment by nijel** [comment]
Apparently there is something broken in using memcached after this, but I failed to find the culprit.

**Comment by mlaggner** [comment]
just tried create a docker instance with python3, but I saw that debian stretch is still using python3.5
what about changing the base image to ubuntu 18.04 after release (should be by the end of April '18) and adopt the dockerfile to use the latest python

**Comment by nijel** [comment]
Switching the base image is an option as well. Still the test failure on Python 3 which happens here is weird.

**Comment by mlaggner** [comment]
switching to ubuntu 18.04 (beta build) and python 3.6 lead me to only 1 error in the test suite:

```
======================================================================
FAIL: test_wrong_path (weblate.trans.tests.test_models.ProjectTest)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/tmp/Weblate-2.20/weblate/trans/tests/test_models.py", line 121, in test_wrong_path
    project.full_clean
  File "/usr/local/lib/python3.6/dist-packages/django/test/testcases.py", line 615, in assertRaisesMessage
    callable_obj(*args, **kwargs)
  File "/usr/lib/python3.6/contextlib.py", line 88, in __exit__
    next(self.gen)
  File "/usr/local/lib/python3.6/dist-packages/django/test/testcases.py", line 590, in _assert_raises_message_cm
    yield cm
AssertionError: ValidationError not raised
```

the only differences to your changes are:
* changed the base image to FROM ubuntu:18.04
* changed cython to cython3
* changed all occurrences of python3.5 to python3.6
* added missind requirements from the Weblate repo:
  * python-levenshtein>=0.12.0
  * filelock>=3.0.1
  * user-agents>=1.1.0

but there are some issues inside weblate with python which I will post as issues in weblate itself

**Comment by mlaggner** [comment]
I get the following error in the admin panel after switching to python 3.6
```
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/dist-packages/weblate/formats/models.py", line 50, in load_data
    fileformat.get_class()
  File "/usr/local/lib/python3.6/dist-packages/weblate/formats/ttkit.py", line 728, in get_class
    raise ImportError('RC not supported on Python 3')
ImportError: RC not supported on Python 3
```

**Comment by nijel** [comment]
File format errors are safe to ignore, it's just to indicate that some feature is not available.

**Pull request merged**
