### PR TITLE
add ldap auth support

### PR DESCRIPTION
**Pull request by glensc**
based on documentation:
https://docs.weblate.org/en/latest/admin/auth.html#ldap-authentication

second part goes to master branch: https://github.com/WeblateOrg/docker/pull/54

### CODE REVIEW

**Comment by glensc** [comment]
btw, it displays rather annoying message in statusbar:

```
Your profile
You have not enabled password authentication, please set the password.
You will be still able to authenticate using third party services.
The password is used to verify important changes on your account.
```

i think password auth should be disabled if ldap auth is enabled. whole point of ldap is to have centralized auth control.

**Comment by glensc** [comment]
also, probably related, i can't save watched projects. i get javascript error on console and no actions being performed

```
#subscriptions
:82/accounts/profile/#subscriptions:1 An invalid form control with name='first_name' is not focusable.
context-menu-content-scripts.js:23 Uncaught TypeError: event.target[matches] is not a function
    at HTMLDocument.<anonymous> (context-menu-content-scripts.js:23)
```

**Comment by nijel** [comment]
You will want to remove  'social_core.backends.email.EmailAuth', when using LDAP, probably worth documenting (also appeared here: https://github.com/WeblateOrg/weblate/issues/1542#issuecomment-316371052)

**Comment by nijel** [comment]
The context-menu-content-scripts.js script seems to come from your browser extension (probably play-to-xbmc), I'm not sure if this is related to the failure or not, but still I recommend trying with disabled extension...

**Comment by nijel** [comment]
Merged with 35028a8 fixing AUTHENTICATION_BACKENDS settings.

**Comment by nijel** [comment]
I've also added docs for these variables in https://github.com/WeblateOrg/weblate/commit/08c7e224e27943bda2bf59829f42e5ef2930aed8, feel free to improve it.

**Comment by glensc** [comment]
also i could not get username and email sync to work, the fields remained blank. i deleted user and logged in again with ldap, because not sure if the fields are synced only on first login or with each login.

the Account tab looks very weird for email. a dropdown with empty choices!!?!

image

**Comment by nijel** [comment]
Is the attribute map correct for your server?

**Comment by glensc** [comment]
not sure which way the map is, weblate to ldap or ldap to weblate attributes

i guessed it's this way as in ldap field name is `mail`:

```
WEBLATE_AUTH_LDAP_USER_ATTR_MAP=first_name:mail,email:mail
```

this showed me email as name. so just need to find proper ldap attribute!

**Comment by glensc** [comment]
ok, works with `WEBLATE_AUTH_LDAP_USER_ATTR_MAP=first_name:cn,email:mail` need to logout to have effect.

**Pull request merged**
