### PR TITLE
Run image as non root

### PR DESCRIPTION
**Pull request by nijel**
Based on https://github.com/WeblateOrg/docker/pull/293

### CODE REVIEW

**Comment by GrahamDumpleton** [comment]
This leaves a security hole because if Linux capabilities for `SETUID` and `SETGID` are not dropped for the container, then someone can become `root` using `su` by setting a password for `root` in the `/etc/passwd` file, since it is now writable.

To fix this, you need to block the ability to use `su` to everyone but `root`.

For a CentOS base image, that would be done by adding `auth requisite pam_deny.so` to `/etc/pam.d/su`. Don't remember off hand what is needed for Debian but likely similar.

If the `sudoers` package is installed, you also need to block anyone but `root` using `sudo`. Specifically disable ability of `wheel` group on CentOS, or maybe `admin` and `sudoers` groups if Debian (I think).

So for CentOS, at same time as making `/etc/passwd` writable, you would need to do:

```
RUN echo "auth requisite pam_deny.so" >> /etc/pam.d/su && \
    sed -i.bak -e 's/^%wheel/# %wheel/' /etc/sudoers && \
    chmod g+w /etc/passwd
```

You should not make `/etc/group` writable as doing so potentially opens up other problems.

**Comment by nijel** [comment]
The pasword is stored in `/etc/shadow` which is not writable. Not that I like idea of updating `/etc/passwd` on startup...

I'll check if we actually need su/sudo (what I think we don't need) so it might be better just to remove those.

**Comment by GrahamDumpleton** [comment]
As legacy, Linux will use a password set in `/etc/passwd`. You just need to add the hashed password in place of the 'x' in the second field of the user entry in `/etc/passwd`.

**Comment by nijel** [comment]
Good point, I didn't realize that.

**Comment by sylvainar** [comment]
Hey!

Thanks for finishing it while I was in vacation, much appreciated 😄

**Comment by nijel** [comment]
There is still some fallout of that, see https://github.com/WeblateOrg/docker/issues/326. Suggestions what might be wrong there are welcome :-)

**Pull request merged**
