### PR TITLE
Allow overriding the email port.

### PR DESCRIPTION
**Pull request by tswast**
[Google Cloud blocks outgoing connections to 587](https://cloud.google.com/compute/docs/networks-and-firewalls#blockedtraffic), but with you can still use a [secure SMTP connection with Mailgun with port 2525](https://cloud.google.com/compute/docs/tutorials/sending-mail/using-mailgun).

### CODE REVIEW

**Comment by nijel** [comment]
Can you please add that to documentation as well (in the Weblate repo)?

**Comment by tswast** [comment]
> Can you please add that to documentation as well (in the Weblate repo)?

Yes. https://github.com/WeblateOrg/weblate/pull/1473

**Comment by nijel** [comment]
Merged, thanks for your contribution!

**Comment by tswast** [comment]
Thank you! I confirmed that I am now able to send email to Mailgun with the [weblate/weblate:edge](https://hub.docker.com/r/weblate/weblate/tags/) image.

**Pull request merged**
