### PR TITLE
logging to stdout and stderr

### LINKED ISSUE #79: logging to stdout
Outputting logs to stdout and stderr is better in Docker.

<bountysource-plugin>

---
Want to back this issue? **[Post a bounty on it!](https://www.bountysource.com/issues/58345361-logging-to-stdout?utm_campaign=plugin&utm_content=tracker%2F21377293&utm_medium=issues&utm_source=github)** We accept bounties via [Bountysource](https://www.bountysource.com/?utm_campaign=plugin&utm_content=tracker%2F21377293&utm_medium=issues&utm_source=github).
</bountysource-plugin>

### LINKED ISSUE #80: Fix /app/data permission on start
On the first run, the `/app/data` directory permission may be wrong, e.g `root:root`

<bountysource-plugin>

---
Want to back this issue? **[Post a bounty on it!](https://www.bountysource.com/issues/58347583-fix-app-data-permission-on-start?utm_campaign=plugin&utm_content=tracker%2F21377293&utm_medium=issues&utm_source=github)** We accept bounties via [Bountysource](https://www.bountysource.com/?utm_campaign=plugin&utm_content=tracker%2F21377293&utm_medium=issues&utm_source=github).
</bountysource-plugin>

### PR DESCRIPTION
**Pull request by tnextday**
close #79 
close #80

### CODE REVIEW

**Comment by tnextday** [comment]
I haven't tested it yet. I'll test it tomorrow.

**Comment by tnextday** [comment]
Done, please review it. @nijel

**Comment by nijel** [comment]
The patch looks good. What I'm not really sure if it's good idea to mix all the logs into one, this would be really messy to process further...

**Comment by tnextday** [comment]
There is a little mess, but I think it is acceptable 😆 

If you want to do statistics, you can use `NGINX_ACCESS_LOG` to output nginx's log to a mounted volume.

```
Postgres is up
Operations to perform:
  Apply all migrations: accounts, addons, admin, auth, authtoken, contenttypes, gitexport, lang, memory, permissions, screenshots, sessions, sites, social_django, trans, wladmin
Running migrations:
  No migrations to apply.
  Your models have changes that are not yet reflected in a migration, and so won't be applied.
  Run 'manage.py makemigrations' to make new migrations, and then re-run 'manage.py migrate' to apply them.

0 static files copied to '/app/data/static', 130 unmodified.
/usr/lib/python2.7/dist-packages/supervisor/options.py:298: UserWarning: Supervisord is running as root and it is searching for its configuration file in default locations (including its current working directory); you probably want to specify a "-c" argument specifying an absolute path to a configuration file for improved security.
  'Supervisord is running as root and it is searching '
2018-05-18 01:25:12,162 CRIT Supervisor running as root (no user in config file)
2018-05-18 01:25:12,162 INFO Included extra file "/etc/supervisor/conf.d/cron.conf" during parsing
2018-05-18 01:25:12,162 INFO Included extra file "/etc/supervisor/conf.d/nginx.conf" during parsing
2018-05-18 01:25:12,162 INFO Included extra file "/etc/supervisor/conf.d/supervisor.conf" during parsing
2018-05-18 01:25:12,162 INFO Included extra file "/etc/supervisor/conf.d/uwsgi.conf" during parsing
2018-05-18 01:25:12,175 INFO RPC interface 'supervisor' initialized
2018-05-18 01:25:12,175 CRIT Server 'unix_http_server' running without any HTTP authentication checking
2018-05-18 01:25:12,179 INFO supervisord started with pid 1
2018-05-18 01:25:13,185 INFO spawned: 'cron' with pid 50
2018-05-18 01:25:13,189 INFO spawned: 'nginx' with pid 51
2018-05-18 01:25:13,192 INFO spawned: 'uwsgi' with pid 52
[uWSGI] getting INI configuration from /usr/share/uwsgi/conf/default.ini
[uWSGI] getting INI configuration from /etc/uwsgi/apps-enabled/weblate.ini
Fri May 18 01:25:13 2018 - *** Starting uWSGI 2.0.14-debian (64bit) on [Fri May 18 01:25:13 2018] ***
Fri May 18 01:25:13 2018 - compiled with version: 6.3.0 20170516 on 17 March 2018 15:41:47
Fri May 18 01:25:13 2018 - os: Linux-4.9.87-linuxkit-aufs #1 SMP Wed Mar 14 15:12:16 UTC 2018
Fri May 18 01:25:13 2018 - nodename: 24e68eeeac1c
Fri May 18 01:25:13 2018 - machine: x86_64
Fri May 18 01:25:13 2018 - clock source: unix
Fri May 18 01:25:13 2018 - pcre jit disabled
Fri May 18 01:25:13 2018 - detected number of CPU cores: 2
Fri May 18 01:25:13 2018 - current working directory: /
Fri May 18 01:25:13 2018 - writing pidfile to /run/uwsgi/app/weblate/pid
Fri May 18 01:25:13 2018 - detected binary path: /usr/bin/uwsgi-core
Fri May 18 01:25:13 2018 - setgid() to 1000
Fri May 18 01:25:13 2018 - setuid() to 1000
Fri May 18 01:25:13 2018 - your memory page size is 4096 bytes
Fri May 18 01:25:13 2018 - detected max file descriptor number: 1048576
Fri May 18 01:25:13 2018 - lock engine: pthread robust mutexes
Fri May 18 01:25:13 2018 - thunder lock: disabled (you can enable it with --thunder-lock)
Fri May 18 01:25:13 2018 - uwsgi socket 0 bound to UNIX address /run/uwsgi/app/weblate/socket fd 3
Fri May 18 01:25:13 2018 - Python version: 2.7.13 (default, Nov 24 2017, 17:33:09)  [GCC 6.3.0 20170516]
Fri May 18 01:25:13 2018 - Python main interpreter initialized at 0x55bb0b1cb0f0
Fri May 18 01:25:13 2018 - python threads support enabled
Fri May 18 01:25:13 2018 - your server socket listen backlog is limited to 100 connections
Fri May 18 01:25:13 2018 - your mercy for graceful operations on workers is 60 seconds
Fri May 18 01:25:13 2018 - mapped 230592 bytes (225 KB) for 2 cores
Fri May 18 01:25:13 2018 - *** Operational MODE: preforking ***
Fri May 18 01:25:13 2018 - added /usr/local/lib/python2.7/dist-packages/ to pythonpath.
2018-05-18 01:25:14,251 INFO success: cron entered RUNNING state, process has stayed up for > than 1 seconds (startsecs)
2018-05-18 01:25:14,251 INFO success: nginx entered RUNNING state, process has stayed up for > than 1 seconds (startsecs)
2018-05-18 01:25:14,254 INFO success: uwsgi entered RUNNING state, process has stayed up for > than 1 seconds (startsecs)
Fri May 18 01:25:14 2018 - WSGI app 0 (mountpoint='') ready in 1 seconds on interpreter 0x55bb0b1cb0f0 pid: 52 (default app)
Fri May 18 01:25:14 2018 - *** uWSGI is running in multiple interpreter mode ***
Fri May 18 01:25:14 2018 - spawned uWSGI master process (pid: 52)
Fri May 18 01:25:14 2018 - spawned uWSGI worker 1 (pid: 66, cores: 1)
Fri May 18 01:25:14 2018 - spawned uWSGI worker 2 (pid: 67, cores: 1)
172.17.0.1 - - [18/May/2018:01:25:39 +0000] "GET /accounts/login/?next=/ HTTP/1.1" 200 2673 "-" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_13_4) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/66.0.3359.170 Safari/537.36"
[pid: 67|app: 0|req: 1/1] 172.17.0.1 () {46 vars in 974 bytes} [Fri May 18 01:25:38 2018] GET /accounts/login/?next=/ => generated 8664 bytes in 695 msecs (HTTP/1.1 200) 8 headers in 405 bytes (1 switches on core 0)
[pid: 66|app: 0|req: 1/2] 172.17.0.1 () {44 vars in 838 bytes} [Fri May 18 01:25:39 2018] GET /js/i18n/ => generated 3217 bytes in 494 msecs (HTTP/1.1 200) 5 headers in 154 bytes (1 switches on core 0)
172.17.0.1 - - [18/May/2018:01:25:39 +0000] "GET /js/i18n/ HTTP/1.1" 200 3217 "http://127.0.0.1:28080/" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_13_4) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/66.0.3359.170 Safari/537.36"
172.17.0.1 - - [18/May/2018:01:25:39 +0000] "GET /static/favicon.ico HTTP/1.1" 200 90022 "http://127.0.0.1:28080/" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_13_4) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/66.0.3359.170 Safari/537.36"
```

**Comment by nijel** [comment]
Merged, thanks for your contribution!

**Comment by nijel** [comment]
Thank you for your report, the issue you have reported has just been fixed by https://github.com/WeblateOrg/docker/pull/81.

* In case you see problem with the fix, please comment on this issue. 
* In case you see similar problem, please open separate issue.
* If you are happy with the outcome, consider supporting Weblate by [donating](https://weblate.org/donate/).

**Pull request merged**
